apiVersion: apps/v1
kind: Deployment
metadata:
  name: json-app-deployment
  labels:
    app: json-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: json-app
  template:
    metadata:
      labels:
        app: json-app
    spec:
      containers:
      - name: json-app
        image: daviddz27/k8s-json-app:0.0.1
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 200m
            memory: 300Mi
          limits:
            memory: 400Mi